
# Workflow Name
name: Auto Deploy Website

# Control when the action will run:
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2.3.1

      - name: Auto Deploy Website
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: website # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
